### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by smallmax00** [biomedia-mira/stochastic_segmentation_networks#1]
Thanks for your work!

Many of the uncertainty related papers generate fancy uncertainty maps like yours, Can I ask how did you generate the visualization of Fig.4 (e) the marginal entropy.

e.g. What colormap did you use? Any post-processing?
Thank you

**Comment by MiguelMonteiro** [comment]
Hello,

The color map used for the uncertainty maps was `cmap='inferno'`.
If the base of the logarithm used to calculating the marginal entropy is the number of classes then the marginal entropies values for each pixel will be bounded between 0 and 1. Thus no further normalisation or post-processing is required.
